src/jtmain/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^admin/', admin.site.urls),
]

src/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.login_to_app, name='login'),
    url(r'^login_to_app/$', views.login_to_app, name='login_to_app'),
    url(r'^logout/$', views.logout_of_app, name='logout_of_app'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserUpdate.as_view(), name='update_user'),
    url(r'^$', views.UserHomeView.as_view(), name='user_home'),
    url(r'^new_post/$', views.AddPostView.as_view(), name='add_post'),
]

src/main/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200, blank=False)
    body = RichTextField()
    author = models.ForeignKey(User)
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=200, blank=True)

src/main/forms.py
from django import forms
from django.forms import Form, ModelForm, ValidationError
from .models import Post
from django.contrib.auth import authenticate, login


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'category']

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PostForm, self).__init__(*args, **kwargs)

    def clean(self):
        """
        We need to do some model validation to ensure the User given is acceptable.

        We also need to make sure we actually have a file.

        :return: dict, the data needed for the model.
        """

        cleaned_data = super(PostForm, self).clean()
        cleaned_data['author'] = self.user

        return cleaned_data


class LoginForm(Form):
    """
    Manage logins to the app.
    """
    username = forms.CharField()
    password = forms.CharField()

    def clean(self):
        """
        Make sure the login worked.

        :return: dict, the cleaned_data.
        """
        user = self.login()

        if not user or not user.is_active:
            raise ValidationError('Sorry that was an invalid login. Please try again.')

        return self.cleaned_data

    def login(self):
        """
        Authenticate the user for logging in.

        :return: User, the authenticated user.
        """
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)

        return user

src/jtmain/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("Excuse the mess we are rebuilding.")

src/main/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, Http404
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, ListView, UpdateView
from .forms import PostForm, LoginForm
from .models import Post, User


def login_to_app(request):
    """
    Login is required to access the main pages.

    The login screen passes data through to here where we can validate and then redirect.

    Currently we redirect to the 'Create Session' page.

    :param request: HTTP request object
    :return: redirect to the load_file window.
    """

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            user = form.login()

            if user:
                login(request, user)

                if request.POST.get('next'):
                    return redirect(request.POST.get('next', 'main:user_home'))
                else:
                    return redirect('main:user_home', )
    else:
        form = LoginForm()
    # If we have reached here, the user has not registered as logged in.
    return render(request, 'login.html', {'form': form})


def logout_of_app(request):
    """
    Basic view to logout a user. Redirects to the login screen.

    :param request: HTTP Request containing the user.
    :return: redirect to login page.
    """
    logout(request)
    return redirect('main:login')


class UserHomeView(ListView):
    """
    The home page for a user.
    """

    model = Post
    context_object_name = 'posts'
    template_name = 'home.html'

    def get_queryset(self):

        return Post.objects.all()


class AddPostView(LoginRequiredMixin, View):
    FORM_CLASS = PostForm
    MODEL = Post

    def get(self, request):

        form = self.FORM_CLASS(request.user)

        return render(request, 'add_post.html', {'form': form})

    def post(self, request, *args, **kwargs):
        """
        Handle the post data from an input file form.

        :param request: HTTP request holding the user.
        :return: redirect: a page showing the new file.
        """
        form = self.FORM_CLASS(request.user, request.POST)

        if form.is_valid():
            new_post = self.MODEL(**form.cleaned_data)
            new_post.save()

            return redirect('main:user_home', )

        return render(request, 'add_post.html', {'form': form})


class UserUpdate(LoginRequiredMixin, UpdateView):
    """
    Manage feed updates.
    """
    model = User
    fields = ['first_name', 'last_name', 'email']
    template_name = 'user_update_form.html'

    def get(self, *args, **kwargs):
        """
        Ensure that the person accessing this feed is allowed access.

        :return: Http response, 404 or successful feed update form.
        """
        user = User.objects.get(pk=kwargs['pk'])

        if self.request.user.pk == user.pk:
            return super(UserUpdate, self).get(*args, **kwargs)
        else:
            return Http404('Sorry you cannot access this user.')

    def get_success_url(self):
        """
        On success return the update page for this user.

        :return: HTTP, response for update page.
        """
        return reverse('main:update_user', kwargs={'pk': self.object.id})

src/main/templates/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load staticfiles %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</body>
</html>

src/main/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}">
    <script src="{% static 'main/js/scroll.js' %}"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div id="body">
        <div id="header">
            <img id="header-img" src="{% static "main/img/Johanssontech-header.png" %}" alt="My image"/>
        </div>
        <div class="container">
            {% for post in posts %}
            <div class="post">
                <h3> {{ post.title }} </h3>
                <p> {{ post.body | safe }} </p>
                <p class="author">{{ post.author.last_name }}, {{ post.author.first_name }} </p><p class="upload_date"></p>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

src/main/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'main:login_to_app' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="jumbotron file_outer">
        {{ form.non_field_errors }}
        <div class="form-group">
            <h3>Login</h3>

            <label for="id_username">Username</label>
            <input type="text" id="id_username" name="username" class="form-control" placeholder="username">
            <label for="id_password">Password</label>
            <input type="password" id="id_password" name="password" class="form-control" placeholder="Password">

            <input type="hidden" name="next" value="{{ next }}" />
            <br/>
        </div>
        <button type="submit" class="btn btn-primary">Log In</button>
        </div>
    </form>
</body>
</html>

src/main/templates/user_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <br>
        <br>
        <input type="submit" value="Update" />
    </form>
</body>
</html>